name: dev-tagging
on:
  push:
    branches:
      - dev
jobs:
  git-tag-job:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Git tagging
        id: git-tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
    outputs:
      new_tag: ${{ steps.git-tag.outputs.new_tag }}
      tag: ${{ steps.git-tag.outputs.tag }}
      part: ${{ steps.git-tag.outputs.part }}
  print-check-tag-job:
    needs: git-tag-job
    runs-on: ubuntu-20.04
    env:
      NEW_TAG: ${{ needs.git-tag-job.outputs.new_tag }}
      TAG: ${{ needs.git-tag-job.outputs.tag }}
      PART: ${{ needs.git-tag-job.outputs.part }}
    steps:
      - name: Print check tag on another job
        run: |
          echo "new_tag = ${NEW_TAG}"
          echo "tag = $TAG"
          echo "part = $PART"
  print-current-branch:
    needs: print-check-tag-job
    runs-on: ubuntu-20.04
    steps:
      - name: Print current branch
        run: |
          git status
          git branch

  # docker-tag:
  #   needs: git-tag
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Pull and push tagged Docker Image
  #       uses: akhilerm/tag-push-action@v1.0.0
  #       with:
  #         src: ghcr.io/tmpImg:latest
  #         dst: |
  #           ghcr.io/tmpImg:${{needs.git-tag.outputs.tag-version}}